name: Terraform Deployment
on:
  push:
    branches:
    - dev

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Github repository
      uses: actions/checkout@v4
      with:
        ref: dev
    - name: List files
      run: |
        ls -la

  terraform-backend-deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
    - name: Clone Github repository
      uses: actions/checkout@v4
      with:
        ref: dev
    - name: Installing Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.11.3"
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform-backend
    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform-backend
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform-backend
    - name: Terraform Apply
      run: terraform apply --auto-approve
      working-directory: ./terraform-backend
